BaseUrl= "https://fjfei.github.io/my_hugo_gh_blog/"
LanguageCode= "en-US"
Title= "Hugo gh-page Air"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2021"
canonifyurls = true

[author]
  name = "fjfei"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "this is my description"
  cover = "images/user.jpg"
  author = "fjfei"
  authorlocation = ""
  authorwebsite = "http://hgithub.com/fjfei"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "fjfei"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
